### ISSUE TITLE
Incorrect file version

### ISSUE THREAD

**Issue by fangs0903** [smallo92/Ymap-YbnMover#5]
It seems that you forgot to update the file. The downloaded version is still 2.2.7.2

**Comment by smallo92** [comment]
No I didn't. When you launch the program it'll prompt you to download 2.2.8.0. Just tested it again and it updates fine.

**Comment by fangs0903** [comment]
Yes, it prompts me to download 2.2.8.0, but the downloaded update.zip file is still 2.2.7.2

**Comment by smallo92** [comment]
Yeah your network is caching an old version or something, it's impossible to be getting an old version. I don't store old versions.

**Comment by fangs0903** [comment]
My fault I use incognito window to download it is no problem
I am very sorry i have waste your time.
